name: Build Docker Images (Matrix)

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Define the matrix for CUDA and Dorado versions supported
        # mind to set properly the "latest" tag in the "tag-latest" job
        cuda_version: [11.8.0, 12.8.0]
        dorado_version: [v0.9.6, v1.0.0]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            bunop/dorado:${{ matrix.dorado_version }}-cuda${{ matrix.cuda_version }}
          build-args: |
            CUDA_VERSION=${{ matrix.cuda_version }}
            DORADO_VERSION=${{ matrix.dorado_version }}
          cache-from: type=registry,ref=bunop/dorado:${{ matrix.dorado_version }}-cuda${{ matrix.cuda_version }}

  tag-latest:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Docker pull and tag latest
        run: |
          docker pull bunop/dorado:v1.0.0-cuda12.8.0
          docker tag bunop/dorado:v1.0.0-cuda12.8.0 bunop/dorado:latest
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker push bunop/dorado:latest
